### ISSUE TITLE
Spec compliance (`--platform`)

### ISSUE THREAD

**Issue by pixelcmtd** [dbrgn/tealdeer#209]
We recently had some internal misconceptions (tldr-pages/tldr#6869) because of clients, especially this one, not complying to the spec by using `-o`/`--os` instead of `-p`/`--platform`. Is that only because of `--pager` and are you planning to fix it?

Things to change in order to conform to the client specification:

- [x] Rename `-o`/`--os` to `-p`/`--platform` → #217 
- [x] When doing a page lookup, ensure that the page name must be lowercased (`tldr AbC should display the page called `abc`) → #227
- [ ] ~~Support the platform `all` which works like the default platform, but lists pages from all platforms when calling `--list` → #229~~

**Comment by CleanMachine1** [comment]
:+1: for fitting spec, makes documentation easier and everyone being able to use the same provided information.

**Comment by niklasmohrin** [comment]
Should we convert your list to issues with a custom label / milestone?

**Comment by dbrgn** [comment]
I decided to drop the issue with the platform type "all" from the spec compliance list, since its place in the spec is disputed (see https://github.com/tldr-pages/tldr/issues/7528 and https://github.com/tldr-pages/tldr/pull/7561). We'll keep tracking those issues, but the compliance work for the client specification v1.5 is done here, I think.
